config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  root to: "tasks#index"

  resources :tasks do
    member do
      get 'invite'
      post 'send_invitation'
    end
  end

  

end

app/models/task.rb
class Task < ActiveRecord::Base
  # belongs_to :user

  has_and_belongs_to_many :users

  # scope :desc, order(created_at: :desc)

  def self.user_name(id)
  	User.where(id: id)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
	# has_many :tasks, dependent: :destroy
	has_and_belongs_to_many :tasks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!

  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :authenticate_user!

	def index
		@tasks = Task.where(user_id: current_user.id).all.order(created_at: :desc)
		@share_tasks=current_user.tasks.all.order(created_at: :desc)
	end

	def new
		@tasks=Task.new
	end

	def create
		@task = current_user.tasks.build(task_params)
		@task.user_id = current_user.id
		if @task.save
			redirect_to root_url, notic: "Successfully Create Task"
		else
			render 'new'
		end
	end

	def show
		@task=Task.where(id: params[:id])
	end

	def invite
		@user=User.new
	end

	def send_invitation
		@email=params[:user][:email]

		@task=Task.where(id: params[:id]).first
		@user=User.where(email: @email).first

		if @user.present?
			@user.tasks.append(@task)
			UserMailer.send_invitation(current_user, @user, @task)
		else
			@user=User.create(email: @email)
			if @user.save
				render 'invite'
			else
				@user.tasks.append(@task)
				UserMailer.send_invitation(current_user, @user, @task)
			end
		end
	end

	private
	def task_params
		params.require(:task).permit(:title, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1>Task Management Application</h1>
<p>Welcome to Task Management Application</p>

<%= link_to "Create New Task", new_task_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManagementApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <% if user_signed_in? %>
			<p>Login as <strong><%= current_user.email %></strong> ||
			<%= link_to "Log Out", destroy_user_session_url, method: :delete %>
		<% else %>
			<%= link_to "Sign In", new_user_session_url %> ||
			<%= link_to "Sign Up", new_user_registration_url %>
		<% end %>
		
<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<h1>Task Management Application</h1>
<p>Welcome to Task Management Application</p>

<%= link_to "Create New Task", new_task_url %> 

<br>

<% if @tasks.present? %>

<h2>List of Your Task </h2>
	<table border=1>
		<tr>
			<th>SN</th>
			<th>Title</th>
			<th>Description</th>
			<th>Action</th>
		</tr>

		<% @tasks.each do |t|%>
		<tr>
			<td><%= t.id %></td>
			<td><%= t.title %></td>
			<td><%= t.description %></td>
			<td><%= link_to "View" , task_url(t.id) %></td>
		</tr>
		<% end %>
	</table>

<% end %>

<% if @share_tasks.present? %>

<h2>List of Share Task with You </h2>

	<table border=1>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Action</th>
		</tr>

		<% @share_tasks.each do |s| %>
		<tr>
			<td><%= s.title %></td>
			<td><%= s.description %></td>
			<td><%= link_to "View", task_url(s.id) %></td>
		</tr>

		<% end %>

	</table>
<% end %>

app/views/tasks/invite.html.erb
<%= simple_form_for @user, :url => send_invitation_task_url, :method => :post do |f| %>
	<%= f.input :email %>
	<%= f.button :submit %>
<% end %>	

app/views/tasks/new.html.erb
<h1>Create New Task</h1>

<%= simple_form_for @tasks do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/tasks/send_invitation.html.erb
<strong><%= @current_user.email %></strong>, you have share <strong><%= @task.title %></strong> with <strong><%= @user.email %></strong>

app/views/tasks/show.html.erb
<table border=1>
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Invite</th>
	</tr>

	<% @task.each do |t| %>
	<tr>
		<td><%= t.title %></td>
		<td><%= t.description %></td>
		<td><%= link_to "Invite Friend", invite_task_url(t.id) %></td>
	</tr>
	<% end %>


</table>